---
version: 1
disable_existing_loggers: true
formatters:
    colored:
        format: "%(asctime)s %(name)s %(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"
        datefmt: "%m/%d/%Y %I:%M:%S"
        reset: true
        log_colors:
            DEBUG: cyan
            INFO: green
            WARNING: yellow
            ERROR: red
            CRITICAL: red,bg_white
        style: "%"
        "()": colorlog.ColoredFormatter
    simple:
        format: "%(asctime)s %(name)s %(levelname)-8s %(message)s"
        datefmt: "%m/%d/%Y %I:%M:%S"
        reset: true
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: colored
        stream: ext://sys.stdout
    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: "/tmp/junk.log"
        mode: a
        maxBytes: 10485760
        backupCount: 5
loggers:
    '':
        level: DEBUG
        handlers:
        - file
        - console
